[package]
name = "echor"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
pretty_assertions.workspace = true
anyhow.workspace = true
